#!/bin/bash -f
#*********************************************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : main_design.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Sun Feb 25 17:51:16 -0500 2024
# SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved. 
#
# usage: main_design.sh [-help]
# usage: main_design.sh [-lib_map_path]
# usage: main_design.sh [-noclean_files]
# usage: main_design.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'main_design.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
#*********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xilinx_vip xpm microblaze_v11_0_4 xil_defaultlib axi_lite_ipif_v3_0_4 mdm_v3_2_19 lmb_v10_v3_0_11 lmb_bram_if_cntlr_v4_0_19 blk_mem_gen_v8_4_4 generic_baseblocks_v2_1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_22 fifo_generator_v13_2_5 axi_data_fifo_v2_1_21 axi_crossbar_v2_1_23 axi_intc_v4_1_15 xlconcat_v2_1_4 xbip_utils_v3_0_10 c_reg_fd_v12_0_6 c_mux_bit_v12_0_6 c_shift_ram_v12_0_14 xbip_dsp48_wrapper_v3_0_4 xbip_pipe_v3_0_6 xbip_dsp48_addsub_v3_0_6 xbip_addsub_v3_0_6 c_addsub_v12_0_14 xlslice_v1_0_2 xlconstant_v1_1_7 lib_cdc_v1_0_2 interrupt_control_v3_1_4 axi_gpio_v2_0_24 axi_vip_v1_1_8 processing_system7_vip_v1_0_10 proc_sys_reset_v5_0_13 lib_pkg_v1_0_2 lib_srl_fifo_v1_0_2 axi_uartlite_v2_0_26 dist_mem_gen_v8_0_13 lib_fifo_v1_0_14 axi_quad_spi_v3_2_21 axi_protocol_converter_v2_1_22)

# Simulation root library directory
sim_lib_dir="vcs_lib"

# Script info
echo -e "main_design.sh - Script generated by export_simulation (Vivado v2020.2 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xilinx_vip $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_axi4streampc.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_axi4pc.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/xil_common_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_pkg.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi4stream_vip_if.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/axi_vip_if.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/clk_vip_if.sv" \
    "C:/Xilinx/Vivado/2020.2/data/xilinx_vip/hdl/rst_vip_if.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xpm $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_fifo/hdl/xpm_fifo.sv" \
    "C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "C:/Xilinx/Vivado/2020.2/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work microblaze_v11_0_4 $vhdlan_opts \
    "$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/9285/hdl/microblaze_v11_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/main_design/ip/main_design_microblaze_0_0/sim/main_design_microblaze_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/66ea/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work mdm_v3_2_19 $vhdlan_opts \
    "$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/8715/hdl/mdm_v3_2_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/main_design/ip/main_design_mdm_0_0/sim/main_design_mdm_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lmb_v10_v3_0_11 $vhdlan_opts \
    "$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/c2ed/hdl/lmb_v10_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/main_design/ip/main_design_dlmb_v10_0/sim/main_design_dlmb_v10_0.vhd" \
    "$ref_dir/../../../bd/main_design/ip/main_design_ilmb_v10_0/sim/main_design_ilmb_v10_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lmb_bram_if_cntlr_v4_0_19 $vhdlan_opts \
    "$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/0b98/hdl/lmb_bram_if_cntlr_v4_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/main_design/ip/main_design_dlmb_bram_if_cntlr_0/sim/main_design_dlmb_bram_if_cntlr_0.vhd" \
    "$ref_dir/../../../bd/main_design/ip/main_design_ilmb_bram_if_cntlr_0/sim/main_design_ilmb_bram_if_cntlr_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_4_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/2985/simulation/blk_mem_gen_v8_4.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/main_design/ip/main_design_lmb_bram_0/sim/main_design_lmb_bram_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/b752/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/ec67/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/af2c/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/276e/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_2_5 $vhdlan_opts \
    "$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/276e/hdl/fifo_generator_v13_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_2_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/276e/hdl/fifo_generator_v13_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_21 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/54c0/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_23 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/bc0a/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/main_design/ip/main_design_xbar_0/sim/main_design_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_intc_v4_1_15 $vhdlan_opts \
    "$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/47b8/hdl/axi_intc_v4_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/main_design/ip/main_design_microblaze_0_axi_intc_0/sim/main_design_microblaze_0_axi_intc_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlconcat_v2_1_4 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/4b67/hdl/xlconcat_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/main_design/ip/main_design_microblaze_0_xlconcat_0/sim/main_design_microblaze_0_xlconcat_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xbip_utils_v3_0_10 $vhdlan_opts \
    "$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/d117/hdl/xbip_utils_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_reg_fd_v12_0_6 $vhdlan_opts \
    "$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/edec/hdl/c_reg_fd_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_mux_bit_v12_0_6 $vhdlan_opts \
    "$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/ecb4/hdl/c_mux_bit_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_shift_ram_v12_0_14 $vhdlan_opts \
    "$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/2598/hdl/c_shift_ram_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/main_design/ip/main_design_Delai_1cycle_A_1/sim/main_design_Delai_1cycle_A_1.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_wrapper_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/cdbf/hdl/xbip_dsp48_wrapper_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_pipe_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/7468/hdl/xbip_pipe_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_dsp48_addsub_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/910d/hdl/xbip_dsp48_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xbip_addsub_v3_0_6 $vhdlan_opts \
    "$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/cfdd/hdl/xbip_addsub_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work c_addsub_v12_0_14 $vhdlan_opts \
    "$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/ebb8/hdl/c_addsub_v12_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/main_design/ip/main_design_Somme_1/sim/main_design_Somme_1.vhd" \
    "$ref_dir/../../../bd/main_design/ip/main_design_c_shift_ram_0_2/sim/main_design_c_shift_ram_0_2.vhd" \
    "$ref_dir/../../../bd/main_design/ip/main_design_substract_0/sim/main_design_substract_0.vhd" \
    "$ref_dir/../../../bd/main_design/ip/main_design_Delai_3cycle_0/sim/main_design_Delai_3cycle_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xlslice_v1_0_2 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/11d0/hdl/xlslice_v1_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/main_design/ip/main_design_xlslice_0_1/sim/main_design_xlslice_0_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/main_design/ip/main_design_Delai_2cycle_0/sim/main_design_Delai_2cycle_0.vhd" \
    "$ref_dir/../../../bd/main_design/ip/main_design_c_addsub_0_2/sim/main_design_c_addsub_0_2.vhd" \
    "$ref_dir/../../../bd/main_design/ip/main_design_Delai_4CYCLES_1_0/sim/main_design_Delai_4CYCLES_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/main_design/ip/main_design_xlslice_0_3/sim/main_design_xlslice_0_3.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xlconstant_v1_1_7 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/fcfc/hdl/xlconstant_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/main_design/ip/main_design_xlconstant_0_0/sim/main_design_xlconstant_0_0.v" \
    "$ref_dir/../../../bd/main_design/ip/main_design_xlconstant_0_1/sim/main_design_xlconstant_0_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/main_design/ip/main_design_mux2_0_0/sim/main_design_mux2_0_0.vhd" \
    "$ref_dir/../../../bd/main_design/ipshared/990d/hdl/myip_S4e_4reg_v1_0_S00_AXI.vhd" \
    "$ref_dir/../../../bd/main_design/ipshared/990d/hdl/myip_S4e_4reg_v1_0.vhd" \
    "$ref_dir/../../../bd/main_design/ip/main_design_myip_S4e_4reg_0_0/sim/main_design_myip_S4e_4reg_0_0.vhd" \
    "$ref_dir/../../../bd/main_design/ip/main_design_myip_S4e_4reg_0_2/sim/main_design_myip_S4e_4reg_0_2.vhd" \
    "$ref_dir/../../../bd/main_design/ip/main_design_myip_S4e_4reg_1_1/sim/main_design_myip_S4e_4reg_1_1.vhd" \
    "$ref_dir/../../../bd/main_design/ip/main_design_Delai_1cycle_A_3/sim/main_design_Delai_1cycle_A_3.vhd" \
    "$ref_dir/../../../bd/main_design/ip/main_design_Somme_3/sim/main_design_Somme_3.vhd" \
    "$ref_dir/../../../bd/main_design/ip/main_design_c_shift_ram_0_4/sim/main_design_c_shift_ram_0_4.vhd" \
    "$ref_dir/../../../bd/main_design/ip/main_design_substract_2/sim/main_design_substract_2.vhd" \
    "$ref_dir/../../../bd/main_design/ip/main_design_Delai_3cycle_2/sim/main_design_Delai_3cycle_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/main_design/ip/main_design_xlslice_0_4/sim/main_design_xlslice_0_4.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/main_design/ip/main_design_Delai_2cycle_2/sim/main_design_Delai_2cycle_2.vhd" \
    "$ref_dir/../../../bd/main_design/ip/main_design_c_addsub_0_4/sim/main_design_c_addsub_0_4.vhd" \
    "$ref_dir/../../../bd/main_design/ip/main_design_Delai_4CYCLES_1_2/sim/main_design_Delai_4CYCLES_1_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/main_design/ip/main_design_xlslice_1_0/sim/main_design_xlslice_1_0.v" \
    "$ref_dir/../../../bd/main_design/ip/main_design_xlconstant_0_2/sim/main_design_xlconstant_0_2.v" \
    "$ref_dir/../../../bd/main_design/ip/main_design_xlconstant_1_0/sim/main_design_xlconstant_1_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/main_design/ip/main_design_mux2_0_1/sim/main_design_mux2_0_1.vhd" \
    "$ref_dir/../../../bd/main_design/ip/main_design_Delai_1cycle_A_4/sim/main_design_Delai_1cycle_A_4.vhd" \
    "$ref_dir/../../../bd/main_design/ip/main_design_Somme_4/sim/main_design_Somme_4.vhd" \
    "$ref_dir/../../../bd/main_design/ip/main_design_c_shift_ram_0_5/sim/main_design_c_shift_ram_0_5.vhd" \
    "$ref_dir/../../../bd/main_design/ip/main_design_substract_3/sim/main_design_substract_3.vhd" \
    "$ref_dir/../../../bd/main_design/ip/main_design_Delai_3cycle_3/sim/main_design_Delai_3cycle_3.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/main_design/ip/main_design_xlslice_0_5/sim/main_design_xlslice_0_5.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/main_design/ip/main_design_Delai_2cycle_3/sim/main_design_Delai_2cycle_3.vhd" \
    "$ref_dir/../../../bd/main_design/ip/main_design_c_addsub_0_5/sim/main_design_c_addsub_0_5.vhd" \
    "$ref_dir/../../../bd/main_design/ip/main_design_Delai_4CYCLES_1_3/sim/main_design_Delai_4CYCLES_1_3.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/main_design/ip/main_design_xlslice_1_1/sim/main_design_xlslice_1_1.v" \
    "$ref_dir/../../../bd/main_design/ip/main_design_xlconstant_0_3/sim/main_design_xlconstant_0_3.v" \
    "$ref_dir/../../../bd/main_design/ip/main_design_xlconstant_1_1/sim/main_design_xlconstant_1_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/main_design/ip/main_design_mux2_0_2/sim/main_design_mux2_0_2.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/ef1e/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/a040/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_24 $vhdlan_opts \
    "$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/4318/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/main_design/ip/main_design_axi_gpio_0_0/sim/main_design_axi_gpio_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_vip_v1_1_8 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/94c3/hdl/axi_vip_v1_1_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work processing_system7_vip_v1_0_10 $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/34f8/hdl/processing_system7_vip_v1_0_vl_rfs.sv" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/main_design/ip/main_design_processing_system7_0_0/sim/main_design_processing_system7_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work proc_sys_reset_v5_0_13 $vhdlan_opts \
    "$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/8842/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/main_design/ip/main_design_rst_clk_wiz_1_100M_0/sim/main_design_rst_clk_wiz_1_100M_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/main_design/ip/main_design_clk_wiz_1_0/main_design_clk_wiz_1_0_clk_wiz.v" \
    "$ref_dir/../../../bd/main_design/ip/main_design_clk_wiz_1_0/main_design_clk_wiz_1_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/0513/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/51ce/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_uartlite_v2_0_26 $vhdlan_opts \
    "$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/5edb/hdl/axi_uartlite_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/main_design/ip/main_design_axi_uartlite_0_0/sim/main_design_axi_uartlite_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work dist_mem_gen_v8_0_13 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/0bf5/simulation/dist_mem_gen_v8_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_fifo_v1_0_14 $vhdlan_opts \
    "$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/a5cb/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_quad_spi_v3_2_21 $vhdlan_opts \
    "$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/63ec/hdl/axi_quad_spi_v3_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/main_design/ip/main_design_axi_quad_spi_0_0/sim/main_design_axi_quad_spi_0_0.vhd" \
    "$ref_dir/../../../bd/main_design/ip/main_design_rst_clk_wiz_1_100M_1_0/sim/main_design_rst_clk_wiz_1_100M_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_protocol_converter_v2_1_22 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/5cee/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/ec67/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/34f8/hdl" +incdir+"$ref_dir/../../../../S4e_Depart.gen/sources_1/bd/main_design/ipshared/d0f7" +incdir+"C:/Xilinx/Vivado/2020.2/data/xilinx_vip/include" \
    "$ref_dir/../../../bd/main_design/ip/main_design_auto_pc_0/sim/main_design_auto_pc_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../bd/main_design/sim/main_design.vhd" \
  2>&1 | tee -a vhdlan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.main_design xil_defaultlib.glbl -o main_design_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./main_design_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./main_design.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key main_design_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc main_design_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./main_design.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: main_design.sh [-help]\n\
Usage: main_design.sh [-lib_map_path]\n\
Usage: main_design.sh [-reset_run]\n\
Usage: main_design.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
