# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/main_design_constr.xdc

# Block Designs: bd/main_design/main_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design || ORIG_REF_NAME==main_design} -quiet] -quiet

# IP: bd/main_design/ip/main_design_microblaze_0_0/main_design_microblaze_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_microblaze_0_0 || ORIG_REF_NAME==main_design_microblaze_0_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_mdm_0_0/main_design_mdm_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_mdm_0_0 || ORIG_REF_NAME==main_design_mdm_0_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_dlmb_v10_0/main_design_dlmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_dlmb_v10_0 || ORIG_REF_NAME==main_design_dlmb_v10_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_ilmb_v10_0/main_design_ilmb_v10_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_ilmb_v10_0 || ORIG_REF_NAME==main_design_ilmb_v10_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_dlmb_bram_if_cntlr_0/main_design_dlmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==main_design_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_ilmb_bram_if_cntlr_0/main_design_ilmb_bram_if_cntlr_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==main_design_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_lmb_bram_0/main_design_lmb_bram_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_lmb_bram_0 || ORIG_REF_NAME==main_design_lmb_bram_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_xbar_0/main_design_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_xbar_0 || ORIG_REF_NAME==main_design_xbar_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_microblaze_0_axi_periph_0/main_design_microblaze_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_microblaze_0_axi_periph_0 || ORIG_REF_NAME==main_design_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_microblaze_0_axi_intc_0/main_design_microblaze_0_axi_intc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_microblaze_0_axi_intc_0 || ORIG_REF_NAME==main_design_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_microblaze_0_xlconcat_0/main_design_microblaze_0_xlconcat_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_microblaze_0_xlconcat_0 || ORIG_REF_NAME==main_design_microblaze_0_xlconcat_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_Delai_1cycle_A_1/main_design_Delai_1cycle_A_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_Delai_1cycle_A_1 || ORIG_REF_NAME==main_design_Delai_1cycle_A_1} -quiet] -quiet

# IP: bd/main_design/ip/main_design_Somme_1/main_design_Somme_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_Somme_1 || ORIG_REF_NAME==main_design_Somme_1} -quiet] -quiet

# IP: bd/main_design/ip/main_design_c_shift_ram_0_2/main_design_c_shift_ram_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_c_shift_ram_0_2 || ORIG_REF_NAME==main_design_c_shift_ram_0_2} -quiet] -quiet

# IP: bd/main_design/ip/main_design_substract_0/main_design_substract_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_substract_0 || ORIG_REF_NAME==main_design_substract_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_Delai_3cycle_0/main_design_Delai_3cycle_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_Delai_3cycle_0 || ORIG_REF_NAME==main_design_Delai_3cycle_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_xlslice_0_1/main_design_xlslice_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_xlslice_0_1 || ORIG_REF_NAME==main_design_xlslice_0_1} -quiet] -quiet

# IP: bd/main_design/ip/main_design_Delai_2cycle_0/main_design_Delai_2cycle_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_Delai_2cycle_0 || ORIG_REF_NAME==main_design_Delai_2cycle_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_c_addsub_0_2/main_design_c_addsub_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_c_addsub_0_2 || ORIG_REF_NAME==main_design_c_addsub_0_2} -quiet] -quiet

# IP: bd/main_design/ip/main_design_Delai_4CYCLES_1_0/main_design_Delai_4CYCLES_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_Delai_4CYCLES_1_0 || ORIG_REF_NAME==main_design_Delai_4CYCLES_1_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_xlslice_0_3/main_design_xlslice_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_xlslice_0_3 || ORIG_REF_NAME==main_design_xlslice_0_3} -quiet] -quiet

# IP: bd/main_design/ip/main_design_xlconstant_0_0/main_design_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_xlconstant_0_0 || ORIG_REF_NAME==main_design_xlconstant_0_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_xlconstant_0_1/main_design_xlconstant_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_xlconstant_0_1 || ORIG_REF_NAME==main_design_xlconstant_0_1} -quiet] -quiet

# IP: bd/main_design/ip/main_design_mux2_0_0/main_design_mux2_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_mux2_0_0 || ORIG_REF_NAME==main_design_mux2_0_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_myip_S4e_4reg_0_0/main_design_myip_S4e_4reg_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_myip_S4e_4reg_0_0 || ORIG_REF_NAME==main_design_myip_S4e_4reg_0_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_myip_S4e_4reg_0_2/main_design_myip_S4e_4reg_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_myip_S4e_4reg_0_2 || ORIG_REF_NAME==main_design_myip_S4e_4reg_0_2} -quiet] -quiet

# IP: bd/main_design/ip/main_design_myip_S4e_4reg_1_1/main_design_myip_S4e_4reg_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_myip_S4e_4reg_1_1 || ORIG_REF_NAME==main_design_myip_S4e_4reg_1_1} -quiet] -quiet

# IP: bd/main_design/ip/main_design_Delai_1cycle_A_3/main_design_Delai_1cycle_A_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_Delai_1cycle_A_3 || ORIG_REF_NAME==main_design_Delai_1cycle_A_3} -quiet] -quiet

# IP: bd/main_design/ip/main_design_Somme_3/main_design_Somme_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_Somme_3 || ORIG_REF_NAME==main_design_Somme_3} -quiet] -quiet

# IP: bd/main_design/ip/main_design_c_shift_ram_0_4/main_design_c_shift_ram_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_c_shift_ram_0_4 || ORIG_REF_NAME==main_design_c_shift_ram_0_4} -quiet] -quiet

# IP: bd/main_design/ip/main_design_substract_2/main_design_substract_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_substract_2 || ORIG_REF_NAME==main_design_substract_2} -quiet] -quiet

# IP: bd/main_design/ip/main_design_Delai_3cycle_2/main_design_Delai_3cycle_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_Delai_3cycle_2 || ORIG_REF_NAME==main_design_Delai_3cycle_2} -quiet] -quiet

# IP: bd/main_design/ip/main_design_xlslice_0_4/main_design_xlslice_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_xlslice_0_4 || ORIG_REF_NAME==main_design_xlslice_0_4} -quiet] -quiet

# IP: bd/main_design/ip/main_design_Delai_2cycle_2/main_design_Delai_2cycle_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_Delai_2cycle_2 || ORIG_REF_NAME==main_design_Delai_2cycle_2} -quiet] -quiet

# IP: bd/main_design/ip/main_design_c_addsub_0_4/main_design_c_addsub_0_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_c_addsub_0_4 || ORIG_REF_NAME==main_design_c_addsub_0_4} -quiet] -quiet

# IP: bd/main_design/ip/main_design_Delai_4CYCLES_1_2/main_design_Delai_4CYCLES_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_Delai_4CYCLES_1_2 || ORIG_REF_NAME==main_design_Delai_4CYCLES_1_2} -quiet] -quiet

# IP: bd/main_design/ip/main_design_xlslice_1_0/main_design_xlslice_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_xlslice_1_0 || ORIG_REF_NAME==main_design_xlslice_1_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_xlconstant_0_2/main_design_xlconstant_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_xlconstant_0_2 || ORIG_REF_NAME==main_design_xlconstant_0_2} -quiet] -quiet

# IP: bd/main_design/ip/main_design_xlconstant_1_0/main_design_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_xlconstant_1_0 || ORIG_REF_NAME==main_design_xlconstant_1_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_mux2_0_1/main_design_mux2_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_mux2_0_1 || ORIG_REF_NAME==main_design_mux2_0_1} -quiet] -quiet

# IP: bd/main_design/ip/main_design_Delai_1cycle_A_4/main_design_Delai_1cycle_A_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_Delai_1cycle_A_4 || ORIG_REF_NAME==main_design_Delai_1cycle_A_4} -quiet] -quiet

# IP: bd/main_design/ip/main_design_Somme_4/main_design_Somme_4.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_Somme_4 || ORIG_REF_NAME==main_design_Somme_4} -quiet] -quiet

# IP: bd/main_design/ip/main_design_c_shift_ram_0_5/main_design_c_shift_ram_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_c_shift_ram_0_5 || ORIG_REF_NAME==main_design_c_shift_ram_0_5} -quiet] -quiet

# IP: bd/main_design/ip/main_design_substract_3/main_design_substract_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_substract_3 || ORIG_REF_NAME==main_design_substract_3} -quiet] -quiet

# IP: bd/main_design/ip/main_design_Delai_3cycle_3/main_design_Delai_3cycle_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_Delai_3cycle_3 || ORIG_REF_NAME==main_design_Delai_3cycle_3} -quiet] -quiet

# IP: bd/main_design/ip/main_design_xlslice_0_5/main_design_xlslice_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_xlslice_0_5 || ORIG_REF_NAME==main_design_xlslice_0_5} -quiet] -quiet

# IP: bd/main_design/ip/main_design_Delai_2cycle_3/main_design_Delai_2cycle_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_Delai_2cycle_3 || ORIG_REF_NAME==main_design_Delai_2cycle_3} -quiet] -quiet

# IP: bd/main_design/ip/main_design_c_addsub_0_5/main_design_c_addsub_0_5.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_c_addsub_0_5 || ORIG_REF_NAME==main_design_c_addsub_0_5} -quiet] -quiet

# IP: bd/main_design/ip/main_design_Delai_4CYCLES_1_3/main_design_Delai_4CYCLES_1_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_Delai_4CYCLES_1_3 || ORIG_REF_NAME==main_design_Delai_4CYCLES_1_3} -quiet] -quiet

# IP: bd/main_design/ip/main_design_xlslice_1_1/main_design_xlslice_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_xlslice_1_1 || ORIG_REF_NAME==main_design_xlslice_1_1} -quiet] -quiet

# IP: bd/main_design/ip/main_design_xlconstant_0_3/main_design_xlconstant_0_3.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_xlconstant_0_3 || ORIG_REF_NAME==main_design_xlconstant_0_3} -quiet] -quiet

# IP: bd/main_design/ip/main_design_xlconstant_1_1/main_design_xlconstant_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_xlconstant_1_1 || ORIG_REF_NAME==main_design_xlconstant_1_1} -quiet] -quiet

# IP: bd/main_design/ip/main_design_mux2_0_2/main_design_mux2_0_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_mux2_0_2 || ORIG_REF_NAME==main_design_mux2_0_2} -quiet] -quiet

# IP: bd/main_design/ip/main_design_axi_gpio_0_0/main_design_axi_gpio_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_axi_gpio_0_0 || ORIG_REF_NAME==main_design_axi_gpio_0_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_processing_system7_0_0/main_design_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_processing_system7_0_0 || ORIG_REF_NAME==main_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_rst_clk_wiz_1_100M_0/main_design_rst_clk_wiz_1_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==main_design_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_clk_wiz_1_0/main_design_clk_wiz_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_clk_wiz_1_0 || ORIG_REF_NAME==main_design_clk_wiz_1_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_axi_uartlite_0_0/main_design_axi_uartlite_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_axi_uartlite_0_0 || ORIG_REF_NAME==main_design_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_axi_quad_spi_0_0/main_design_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_axi_quad_spi_0_0 || ORIG_REF_NAME==main_design_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_rst_clk_wiz_1_100M_1_0/main_design_rst_clk_wiz_1_100M_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_rst_clk_wiz_1_100M_1_0 || ORIG_REF_NAME==main_design_rst_clk_wiz_1_100M_1_0} -quiet] -quiet

# IP: bd/main_design/ip/main_design_auto_pc_0/main_design_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_design_auto_pc_0 || ORIG_REF_NAME==main_design_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/alexi/OneDrive/S4/APP4/S4e_Depart/S4e_Depart.gen/sources_1/bd/main_design/main_design_ooc.xdc
