# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Alexi/OneDrive/S4/APP4/S4e_Depart_etud/S4e_Depart.srcs/sources_1/bd/main_design/ip/main_design_ilmb_bram_if_cntlr_0/main_design_ilmb_bram_if_cntlr_0.xci
# IP: The module: 'main_design_ilmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Alexi/OneDrive/S4/APP4/S4e_Depart_etud/S4e_Depart.gen/sources_1/bd/main_design/ip/main_design_ilmb_bram_if_cntlr_0/main_design_ilmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_design_ilmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/Alexi/OneDrive/S4/APP4/S4e_Depart_etud/S4e_Depart.srcs/sources_1/bd/main_design/ip/main_design_ilmb_bram_if_cntlr_0/main_design_ilmb_bram_if_cntlr_0.xci
# IP: The module: 'main_design_ilmb_bram_if_cntlr_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Alexi/OneDrive/S4/APP4/S4e_Depart_etud/S4e_Depart.gen/sources_1/bd/main_design/ip/main_design_ilmb_bram_if_cntlr_0/main_design_ilmb_bram_if_cntlr_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_design_ilmb_bram_if_cntlr_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
